apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - name: kafka
      port: 9092       # Exposed port
      targetPort: 9092 # Kafka container's port
  selector:
    app: kafka
